\i clean_tiny_geometries.sql
\i clean_road_refs.sql
\i make_valid.sql
\i add_table_osm_roads_n_railways.sql
\i add_table_osm_roads_n_railways_gen0.sql
\i add_table_osm_roads_n_railways_gen1.sql
\i add_table_osm_roads_for_labels.sql
\i add_table_osm_waterways_for_labels.sql
\i add_table_osm_areas_for_labels.sql
